In [23]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
import warnings

#settings
warnings.filterwarnings("ignore")

In [24]:
def data_selection(position):
    df = pd.read_csv("../raw_data/data_cleaned.csv")
    df_selected = df[df['position']==position]
    return df_selected

In [25]:
def data_scaling(df):
    minmaxscaler = MinMaxScaler()
    df['highest_market_value_in_eur']= minmaxscaler.fit_transform(df[['highest_market_value_in_eur']])
    return df

In [26]:
def data_encoding(df):
    ohe = OneHotEncoder(sparse=False)
    encoder =  OrdinalEncoder()
    df[ohe.get_feature_names_out()] = ohe.fit_transform(df[['foot']])
    df['country_of_citizenship'] = encoder.fit_transform(df[['country_of_citizenship']])
    return df

In [27]:
def drop_columns(df):
    df.drop(columns=['Unnamed: 0','foot','position'], inplace = True)
    return df

In [28]:
def data_preprocess(df):
    df = data_scaling(df)
    df = data_encoding(df)
    df = drop_columns(df)
    return df

In [29]:
df = data_selection('Attack')
data_preprocess(df)

,games_2022,minutes_played_2022,goals_2022,assists_2022,goals_against_2022,goals_for_2022,height_in_cm,age,country_of_citizenship,term_days_remaining,highest_market_value_in_eur,yellow_cards_2022,market_value_in_eur,foot_Both,foot_Left,foot_Right
0,0.0,0.0,0.0,0.0,0.0,0.0,183,35,52.0,97,0.001375,0.0,125000.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,188,39,113.0,281,0.004876,0.0,150000.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,184,34,110.0,97,0.022378,0.0,300000.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,180,36,42.0,97,0.019877,0.0,500000.0,0.0,0.0,1.0
9,0.0,0.0,0.0,0.0,0.0,0.0,184,35,52.0,97,0.000875,0.0,100000.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14940,22.0,1777.0,7.0,2.0,32.0,29.0,174,25,37.0,1558,0.044881,1.0,9000000.0,0.0,1.0,0.0
14941,19.0,1249.0,3.0,3.0,24.0,31.0,169,24,10.0,828,0.039880,1.0,6500000.0,0.0,0.0,1.0
14942,17.0,1122.0,5.0,7.0,23.0,29.0,173,37,66.0,97,0.019877,2.0,500000.0,0.0,0.0,1.0
14945,1.0,2.0,0.0,0.0,1.0,0.0,183,20,39.0,1558,0.007376,0.0,1300000.0,0.0,0.0,1.0
14960,17.0,1324.0,2.0,1.0,22.0,24.0,170,22,10.0,463,0.079885,0.0,10000000.0,0.0,0.0,1.0